import type { GrammarDrill } from "./grammar-a1";

export const GRAMMAR_DRILLS_B1: GrammarDrill[] = [
  {
    unit: "work",
    prompt: "Ես գրասենյակում եմ աշխատում։",
    correct: "I work in an office",
    wrong: ["I work on an office", "I work at office", "I am work in office"],
    explanation: "in an office. a/an before job place.",
  },
  {
    unit: "work",
    prompt: "Ես պատասխանատու եմ այս նախագծի համար։",
    correct: "I am responsible for this project",
    wrong: ["I am responsible of this project", "I responsible for this", "I am responsible this project"],
    explanation: "responsible for. Not of.",
  },
  {
    unit: "work",
    prompt: "Նախագիծը ավարտված է։ Passive.",
    correct: "The project is finished",
    wrong: ["The project finished is", "The project is finish", "The project has finish"],
    explanation: "be + past participle.",
  },
  {
    unit: "health",
    prompt: "Ես գլխացավ ունեմ։",
    correct: "I have a headache",
    wrong: ["I have headache", "I am headache", "I have the headache always"],
    explanation: "have a headache. Keep a.",
  },
  {
    unit: "health",
    prompt: "Ես ավելի վատ եմ զգում։",
    correct: "I feel worse",
    wrong: ["I feel more bad", "I feel worst", "I am feel worse"],
    explanation: "bad → worse. Not more bad.",
  },
  {
    unit: "health",
    prompt: "Ես պետք է հանգստանամ։",
    correct: "I need to rest",
    wrong: ["I need rest to", "I must to rest", "I need resting"],
    explanation: "need to + verb.",
  },
  {
    unit: "opinions",
    prompt: "Ես կարծում եմ որ սա ճիշտ է։",
    correct: "I think that this is right",
    wrong: ["I think this be right", "I am think this is right", "I think to this is right"],
    explanation: "I think that + clause.",
  },
  {
    unit: "opinions",
    prompt: "Ես մնում եմ որովհետև հոգնած եմ։ Reason.",
    correct: "because",
    wrong: ["but", "so only", "although"],
    explanation: "որովհետև = because. but = contrast.",
  },
  {
    unit: "opinions",
    prompt: "Ես համաձայն եմ քո կարծիքի հետ։",
    correct: "I agree with your opinion",
    wrong: ["I agree your opinion", "I am agree with you", "I agree to your opinion"],
    explanation: "agree with. Not agree to a person.",
  },
  {
    unit: "plans",
    prompt: "Եթե ժամանակ ունենամ կգամ։ First conditional.",
    correct: "If I have time I will come",
    wrong: ["If I will have time I come", "If I have time I come will", "If I had time I will come"],
    explanation: "If + present, will + verb.",
  },
  {
    unit: "plans",
    prompt: "Կուզենայի սուրճ խմել։",
    correct: "I would like to drink coffee",
    wrong: ["I would like drink coffee", "I will like to drink coffee", "I like would coffee"],
    explanation: "would like to + verb.",
  },
  {
    unit: "plans",
    prompt: "Հենց որ ժամանակ ունենամ կզանգեմ։",
    correct: "As soon as I have time I will call",
    wrong: ["As soon as I will have time I call", "Soon I have time I call", "When I will have time I call"],
    explanation: "as soon as + present, will.",
  },
  {
    unit: "experiences",
    prompt: "Ես այնտեղ եղել եմ։ Life experience.",
    correct: "I have been there",
    wrong: ["I have gone there yesterday", "I was being there", "I have be there"],
    explanation: "have been = experience. Yesterday → past simple.",
  },
  {
    unit: "experiences",
    prompt: "Դու երբևէ այնտեղ եղել ես։",
    correct: "Have you ever been there",
    wrong: ["Did you ever been there", "Have you never been there", "Were you ever be there"],
    explanation: "Have you ever + past participle.",
  },
  {
    unit: "experiences",
    prompt: "Ես դեռ չեմ որոշել։",
    correct: "I have not decided yet",
    wrong: ["I did not decided yet", "I have not decide yet", "I yet have not decide"],
    explanation: "have not + participle + yet.",
  },
  {
    unit: "reasons",
    prompt: "Չնայած դժվար է ես համաձայն եմ։",
    correct: "Although it is difficult I agree",
    wrong: ["Because it is difficult I agree", "Although it difficult I agree", "Despite it is difficult I agree"],
    explanation: "although + clause. despite + noun.",
  },
  {
    unit: "reasons",
    prompt: "Իմ կարծիքով սա ճիշտ է։",
    correct: "In my opinion this is right",
    wrong: ["On my opinion this is right", "In my think this is right", "According my opinion"],
    explanation: "in my opinion.",
  },
  {
    unit: "reasons",
    prompt: "Ես հոգնած եմ դրա համար մնում եմ։ Result.",
    correct: "that's why",
    wrong: ["because of why", "although", "for example"],
    explanation: "that's why = result. because = reason.",
  },
];
