import type { GrammarDrill } from "./grammar-a1";

export const GRAMMAR_DRILLS_A2: GrammarDrill[] = [
  {
    unit: "city",
    prompt: "Դպրոցը քաղաքում է։ Choose the preposition.",
    correct: "in the city",
    wrong: ["on the city", "at the city", "to the city"],
    explanation: "in the city. on = վրա, at = մի կետում.",
  },
  {
    unit: "city",
    prompt: "Բանկը այգու ___ է։",
    correct: "next to",
    wrong: ["behind", "between", "far"],
    explanation: "կողքին = next to. behind = հետևում.",
  },
  {
    unit: "city",
    prompt: "Խանութը ձախ է։",
    correct: "on the left",
    wrong: ["in the left", "at left", "to left"],
    explanation: "on the left / on the right.",
  },
  {
    unit: "travel",
    prompt: "Ինձ տոմս է պետք։",
    correct: "I need a ticket",
    wrong: ["I need ticket", "I need the tickets", "I need an ticket"],
    explanation: "a ticket. a + consonant.",
  },
  {
    unit: "travel",
    prompt: "Ես ավտոբուս եմ նստում։",
    correct: "I take the bus",
    wrong: ["I take bus", "I sit a bus", "I go the bus"],
    explanation: "take the bus. Article stays.",
  },
  {
    unit: "travel",
    prompt: "Ինձ քարտեզ է պետք։",
    correct: "I need a map",
    wrong: ["I need map", "I need an map", "I need the maps"],
    explanation: "a map, not map.",
  },
  {
    unit: "past",
    prompt: "Yesterday I ___ home.",
    correct: "went",
    wrong: ["goed", "go", "was go"],
    explanation: "go → went. Not goed.",
  },
  {
    unit: "past",
    prompt: "Ես դպրոց չգնացի։",
    correct: "I did not go",
    wrong: ["I did not went", "I not go", "I don't went"],
    explanation: "did not + base verb. Not did not went.",
  },
  {
    unit: "past",
    prompt: "___ you see my friend?",
    correct: "Did",
    wrong: ["Do", "Does", "Was"],
    explanation: "Past question = Did you + verb.",
  },
  {
    unit: "future",
    prompt: "Վաղը ես տուն կգնամ։ Already decided now?",
    correct: "I am going to go home",
    wrong: ["I will to go home", "I going home", "I go to home tomorrow"],
    explanation: "going to = plan. will = later decision.",
  },
  {
    unit: "future",
    prompt: "Ես ուշ չեմ լինի։",
    correct: "I will not be late",
    wrong: ["I will not late", "I am not will late", "I don't will late"],
    explanation: "will not + be + adjective.",
  },
  {
    unit: "future",
    prompt: "Ես պետք է գնամ։ Strong obligation.",
    correct: "I must go",
    wrong: ["I should go", "I can go", "I will go"],
    explanation: "must = պետք է. should = խորհուրդ.",
  },
  {
    unit: "compare",
    prompt: "Այս հացը ավելի էժան է քան այդը։",
    correct: "cheaper than",
    wrong: ["more cheaper than", "cheaper then", "cheap than"],
    explanation: "short adjective + -er + than. Not more cheaper.",
  },
  {
    unit: "compare",
    prompt: "Այս հյուրանոցը ավելի թանկ է։",
    correct: "more expensive",
    wrong: ["expensiver", "more cheaper", "too expensiveer"],
    explanation: "long adjective → more + adjective.",
  },
  {
    unit: "compare",
    prompt: "Այս հյուրանոցը շատ թանկ է։ Too much.",
    correct: "too expensive",
    wrong: ["very too expensive", "enough expensive", "more too"],
    explanation: "too = չափից շատ. very = շատ.",
  },
  {
    unit: "invites",
    prompt: "Կուզես թեյ։ Polite offer.",
    correct: "Would you like tea",
    wrong: ["Do you like tea now", "You like tea", "Will you like tea"],
    explanation: "Would you like = offer. Do you like = habit.",
  },
  {
    unit: "invites",
    prompt: "Եկ գնանք այգի։",
    correct: "Let us go to the park",
    wrong: ["Let we go to the park", "Let's to go to the park", "We let go park"],
    explanation: "Let's + verb. No to.",
  },
  {
    unit: "invites",
    prompt: "Ազատ ես վաղը։",
    correct: "Are you free tomorrow",
    wrong: ["Do you free tomorrow", "You are free tomorrow?", "Is you free tomorrow"],
    explanation: "Are you + adjective.",
  },
];
