import type { A1UnitKey } from "./lexicon-a1";
import type { Lexeme } from "./types";

function entry(
  key: string,
  hy: string,
  en: string,
  ru: string,
  hyPron: string,
  enPron: string,
  ruPron: string,
  exampleHy: string,
  exampleEn: string,
  exampleRu: string,
): Lexeme {
  return { key, hy, en, ru, hyPron, enPron, ruPron, exampleHy, exampleEn, exampleRu };
}

export const LEXICON_A1_EXTRAS: Partial<Record<A1UnitKey, Lexeme[]>> = {
  greetings: [
    entry("what-q", "ինչ", "what", "что", "inch", "wot", "chto", "Ի՞նչ է սա։", "What is this?", "Что это?"),
    entry("how-q", "ինչպես", "how", "как", "inchpes", "how", "kak", "Ինչպե՞ս ես։", "How are you?", "Как дела?"),
  ],
  introduce: [
    entry("it", "այն", "it", "оно", "ayn", "it", "ono", "Այն գիրք է։", "It is a book.", "Это книга."),
    entry("country", "երկիր", "country", "страна", "yerkir", "kun-tree", "strana", "Հայաստանը գեղեցիկ երկիր է։", "Armenia is a beautiful country.", "Армения красивая страна."),
    entry("yerevan", "Երևան", "Yerevan", "Ереван", "Yerevan", "ye-re-van", "Yerevan", "Ես Երևանում եմ ապրում։", "I live in Yerevan.", "Я живу в Ереване."),
    entry("russia", "Ռուսաստան", "Russia", "Россия", "Rusastan", "rush-uh", "Rossiya", "Նա Ռուսաստանից է։", "He is from Russia.", "Он из России."),
    entry("who-q", "ով", "who", "кто", "ov", "hoo", "kto", "Ո՞վ է նա։", "Who is he?", "Кто он?"),
    entry("how-old", "քանի տարեկան", "how old", "сколько лет", "kani tarekan", "how ohld", "skolko let", "Քանի՞ տարեկան ես։", "How old are you?", "Сколько тебе лет?"),
  ],
  family: [
    entry("has", "ունի", "has", "у него есть", "uni", "haz", "u nego yest", "Նա եղբայր ունի։", "He has a brother.", "У него есть брат."),
    entry("his", "նրա", "his", "его", "nra", "hiz", "yevo", "Սա նրա հայրն է։", "This is his father.", "Это его папа."),
    entry("her", "նրա", "her", "её", "nra", "hur", "yeyo", "Սա նրա մայրն է։", "This is her mother.", "Это её мама."),
    entry("our", "մեր", "our", "наш", "mer", "owr", "nash", "Սա մեր տունն է։", "This is our home.", "Это наш дом."),
    entry("their", "նրանց", "their", "их", "nrants", "thair", "ikh", "Սա նրանց երեխան է։", "This is their child.", "Это их ребёнок."),
    entry("man", "տղամարդ", "man", "мужчина", "tghamard", "man", "muzhchina", "Այս տղամարդը ուսանող է։", "This man is a student.", "Этот мужчина студент."),
    entry("woman", "կին մարդ", "woman", "женщина", "kin mard", "woo-man", "zhenshchina", "Այս կինը ուսուցչուհի է։", "This woman is a teacher.", "Эта женщина учительница."),
    entry("boy", "տղա", "boy", "мальчик", "tgha", "boy", "malchik", "Այս տղան ուսանող է։", "This boy is a student.", "Этот мальчик студент."),
    entry("girl", "աղջիկ", "girl", "девочка", "aghjik", "gurl", "devochka", "Այս աղջիկը այստեղ է։", "This girl is here.", "Эта девочка здесь."),
    entry("people", "մարդիկ", "people", "люди", "mardik", "pee-puhl", "lyudi", "Այս մարդիկ ընկերներ են։", "These people are friends.", "Эти люди друзья."),
  ],
  numbers: [
    entry("tuesday", "երեքշաբթի", "Tuesday", "вторник", "yerekshabti", "tooze-day", "vtornik", "Երեքշաբթի ես տանն եմ։", "I am at home on Tuesday.", "Во вторник я дома."),
    entry("friday", "ուրբաթ", "Friday", "пятница", "urbat", "fry-day", "pyatnitsa", "ուրբաթ ես աշխատում եմ։", "I work on Friday.", "В пятницу я работаю."),
    entry("sunday", "կիրակի", "Sunday", "воскресенье", "kiraki", "sun-day", "voskresenye", "Կիրակի ես տանն եմ։", "I am at home on Sunday.", "В воскресенье я дома."),
    entry("january", "հունվար", "January", "январь", "hunvar", "jan-you-ery", "yanvar", "Ես հունվարին եմ այստեղ։", "I am here in January.", "Я здесь в январе."),
    entry("july", "հուլիս", "July", "июль", "hulis", "joo-ly", "iyul", "Հուլիսը տաք է։", "July is hot.", "Июль жаркий."),
    entry("oclock", "ժամը", "o'clock", "час", "zhamy", "o-clock", "chas", "Ժամը տասն է։", "It is ten o'clock.", "Сейчас десять часов."),
    entry("wednesday", "չորեքշաբթի", "Wednesday", "среда", "choreqshabti", "wenz-day", "sreda", "Չորեքշաբթի ես տանն եմ։", "I am at home on Wednesday.", "В среду я дома."),
    entry("thursday", "հինգշաբթի", "Thursday", "четверг", "hingshabti", "thurz-day", "chetverg", "Հինգշաբթի ես աշխատում եմ։", "I work on Thursday.", "В четверг я работаю."),
    entry("saturday", "շաբաթ օր", "Saturday", "суббота", "shabat or", "sat-ur-day", "subbota", "Շաբաթ ես տանն եմ։", "I am at home on Saturday.", "В субботу я дома."),
    entry("march", "մարտ", "March", "март", "mart", "march", "mart", "Մարտին ցուրտ է։", "It is cold in March.", "В марте холодно."),
    entry("december", "դեկտեմբեր", "December", "декабрь", "dektember", "di-sem-ber", "dekabr", "Դեկտեմբերը ցուրտ է։", "December is cold.", "Декабрь холодный."),
    entry("week-a1", "շաբաթ", "week", "неделя", "shabat", "week", "nedelya", "Այս շաբաթ ես զբաղված եմ։", "I am busy this week.", "На этой неделе я занят."),
    entry("when-q", "երբ", "when", "когда", "yerb", "wen", "kogda", "Ե՞րբ ես աշխատում։", "When do you work?", "Когда ты работаешь?"),
  ],
  food: [
    entry("article-an", "մի", "an", "один", "mi", "an", "odin", "Սա մի խնձոր է։", "This is an apple.", "Это яблоко."),
    entry("article-the", "այդ", "the", "этот", "ayd", "thuh", "etot", "Այդ հացը լավ է։", "The bread is good.", "Этот хлеб хороший."),
    entry("juice", "հյութ", "juice", "сок", "hyut", "joos", "sok", "Ես հյութ եմ ուզում։", "I want juice.", "Я хочу сок."),
    entry("drink", "խմիչք", "drink", "напиток", "khmichk", "drink", "napitok", "Ես խմիչք եմ ուզում։", "I want a drink.", "Я хочу напиток."),
    entry("egg", "ձու", "egg", "яйцо", "dzu", "eg", "yaytso", "Ես մի ձու եմ ուզում։", "I want an egg.", "Я хочу яйцо."),
    entry("rice", "բրինձ", "rice", "рис", "brindz", "rys", "ris", "Ես բրինձ եմ ուզում։", "I want rice.", "Я хочу рис."),
    entry("hungry", "քաղցած", "hungry", "голодный", "khaghtsats", "hung-gree", "golodny", "Ես քաղցած եմ։", "I am hungry.", "Я голодный."),
  ],
  places: [
    entry("room", "սենյակ", "room", "комната", "senyak", "room", "komnata", "Սենյակը մեծ է։", "The room is big.", "Комната большая."),
    entry("kitchen", "խոհանոց", "kitchen", "кухня", "khohanots", "kich-en", "kukhnya", "Խոհանոցը այստեղ է։", "The kitchen is here.", "Кухня здесь."),
    entry("table", "սեղան", "table", "стол", "seghan", "tay-buhl", "stol", "Գիրքը սեղանի վրա է։", "The book is on the table.", "Книга на столе."),
    entry("chair", "աթոռ", "chair", "стул", "ator", "chair", "stul", "Աթոռը սենյակում է։", "The chair is in the room.", "Стул в комнате."),
    entry("door", "դուռ", "door", "дверь", "dur", "dor", "dver", "Դուռը բաց է։", "The door is open.", "Дверь открыта."),
    entry("in-prep", "մեջ", "in", "в", "mej", "in", "v", "Աթոռը սենյակում է։", "The chair is in the room.", "Стул в комнате."),
    entry("on-prep", "վրա", "on", "на", "vra", "on", "na", "Գիրքը սեղանի վրա է։", "The book is on the table.", "Книга на столе."),
    entry("at-prep", "մոտ", "at", "у", "mot", "at", "u", "Ես դպրոցում եմ։", "I am at school.", "Я в школе."),
    entry("under", "տակ", "under", "под", "tak", "un-der", "pod", "Աթոռը սեղանի տակ է։", "The chair is under the table.", "Стул под столом."),
    entry("there-is", "կա", "there is", "есть", "ka", "thair iz", "yest", "Սենյակում աթոռ կա։", "There is a chair in the room.", "В комнате есть стул."),
    entry("bedroom", "ննջասենյակ", "bedroom", "спальня", "nnjasenyak", "bed-room", "spalnya", "Ննջասենյակը փոքր է։", "The bedroom is small.", "Спальня маленькая."),
    entry("window", "պատուհան", "window", "окно", "patuhan", "win-doh", "okno", "Պատուհանը բաց է։", "The window is open.", "Окно открыто."),
    entry("in-front", "առջևում", "in front of", "перед", "arjevum", "in frunt ov", "pered", "Դպրոցը տան առջևում է։", "The school is in front of the house.", "Школа перед домом."),
    entry("left-dir", "ձախ", "left", "налево", "dzakh", "left", "nalevo", "Խանութը ձախ է։", "The shop is on the left.", "Магазин налево."),
    entry("right-dir", "աջ", "right", "направо", "aj", "rite", "napravo", "Դպրոցը աջ է։", "The school is on the right.", "Школа направо."),
    entry("car", "մեքենա", "car", "машина", "meqena", "kar", "mashina", "Ես մեքենա ունեմ։", "I have a car.", "У меня есть машина."),
    entry("taxi", "տաքսի", "taxi", "такси", "taqsi", "tak-see", "taksi", "Ես տաքսի եմ նստում։", "I take a taxi.", "Я еду на такси."),
    entry("that-dem", "այն", "that", "тот", "ayn", "that", "tot", "Այն տունը մեծ է։", "That house is big.", "Тот дом большой."),
    entry("these-dem", "սրանք", "these", "эти", "srank", "theez", "eti", "Սրանք իմ գրքերն են։", "These are my books.", "Это мои книги."),
    entry("those-dem", "դրանք", "those", "те", "drank", "thohz", "te", "Դրանք իմ աթոռներն են։", "Those are my chairs.", "То мои стулья."),
  ],
};

export const LEXICON_A1_MORE: Record<
  "routine" | "shopping" | "hobbies" | "school" | "everyday" | "review",
  Lexeme[]
> = {
  routine: [
    entry("today", "այսօր", "today", "сегодня", "aysor", "tuh-day", "sevodnya", "Այսօր աշխատում եմ։", "I work today.", "Я сегодня работаю."),
    entry("now", "հիմա", "now", "сейчас", "hima", "now", "seychas", "Հիմա տանն եմ։", "I am at home now.", "Я сейчас дома."),
    entry("always", "միշտ", "always", "всегда", "misht", "awl-wayz", "vsegda", "Ես միշտ առավոտյան եմ ուտում։", "I always eat in the morning.", "Я всегда ем утром."),
    entry("usually", "սովորաբար", "usually", "обычно", "sovorabar", "yoo-zhoo-uh-lee", "obychno", "Ես սովորաբար ժամը ութին եմ արթնանում։", "I usually wake up at eight.", "Я обычно просыпаюсь в восемь."),
    entry("sometimes", "երբեմն", "sometimes", "иногда", "yerbemn", "sum-tymz", "inogda", "երբեմն տանն եմ աշխատում։", "I sometimes work at home.", "Я иногда работаю дома."),
    entry("never-freq", "երբեք ոչ", "never", "никогда", "yerbek voch", "nev-er", "nikogda", "Ես երբեք ուշ չեմ գալիս։", "I never come late.", "Я никогда не прихожу поздно."),
    entry("morning-time", "առավոտ", "morning", "утро", "aravot", "mor-ning", "utra", "Առավոտյան ես ուտում եմ։", "I eat in the morning.", "Утром я ем."),
    entry("evening", "երեկո", "evening", "вечер", "ereko", "eev-ning", "vecher", "Երեկոյան տանն եմ։", "I am home in the evening.", "Вечером я дома."),
    entry("eat", "ուտում եմ", "I eat", "я ем", "utum em", "eye eet", "ya yem", "Ես ամեն օր ուտում եմ։", "I eat every day.", "Я ем каждый день."),
    entry("work-verb", "աշխատում եմ", "I work", "я работаю", "ashkhatum em", "eye werk", "ya rabotayu", "Ես ամեն օր աշխատում եմ։", "I work every day.", "Я работаю каждый день."),
    entry("do-not", "չեմ", "I do not", "я не", "chem", "eye do not", "ya ne", "Ես երեկոյան չեմ աշխատում։", "I do not work in the evening.", "Я вечером не работаю."),
    entry("she-works", "նա աշխատում է", "she works", "она работает", "na ashkhatum e", "she werks", "ona rabotayet", "Նա ամեն օր աշխատում է։", "She works every day.", "Она работает каждый день."),
    entry("wake", "արթնանում եմ", "I wake up", "я просыпаюсь", "artnanum em", "eye wayk up", "ya prosypayus", "Ես առավոտյան եմ արթնանում։", "I wake up in the morning.", "Я просыпаюсь утром."),
    entry("sleep", "քնում եմ", "I sleep", "я сплю", "knum em", "eye sleep", "ya splyu", "Ես երեկոյան եմ քնում։", "I sleep in the evening.", "Я сплю вечером."),
    entry("monday", "երկուշաբթի", "Monday", "понедельник", "yerkushabti", "mun-day", "ponedelnik", "Երկուշաբթի աշխատում եմ։", "I work on Monday.", "В понедельник я работаю."),
    entry("every-day", "ամեն օր", "every day", "каждый день", "amen or", "ev-ree day", "kazhdy den", "Ես ամեն օր գնում եմ դպրոց։", "I go to school every day.", "Я каждый день хожу в школу."),
  ],
  shopping: [
    entry("buy", "գնել", "to buy", "купить", "gnel", "too by", "kupit", "Ես ուզում եմ հաց գնել։", "I want to buy bread.", "Я хочу купить хлеб."),
    entry("price", "գին", "price", "цена", "gin", "prys", "tsena", "Գինը լավ է։", "The price is good.", "Цена хорошая."),
    entry("money", "փող", "money", "деньги", "pogh", "mun-ee", "dengi", "Ինձ փող է պետք։", "I need money.", "Мне нужны деньги."),
    entry("how-much", "որքան", "how much", "сколько стоит", "vorkan", "how much", "skolko stoit", "Որքա՞ն է գինը։", "How much is the price?", "Сколько стоит?"),
    entry("clothes", "հագուստ", "clothes", "одежда", "hagust", "klohz", "odezhda", "Ես հագուստ եմ ուզում գնել։", "I want to buy clothes.", "Я хочу купить одежду."),
    entry("size", "չափս", "size", "размер", "chaps", "syz", "razmer", "Ինձ այս չափսն է պետք։", "I need this size.", "Мне нужен этот размер."),
    entry("card", "քարտ", "card", "карта", "kart", "kard", "karta", "Ես քարտով եմ վճարում։", "I pay by card.", "Я плачу картой."),
    entry("change", "մանր", "change", "сдача", "manr", "chaynj", "sdacha", "Ինձ մանր տվեք։", "Give me the change.", "Дайте сдачу."),
    entry("pay", "վճարել", "to pay", "платить", "vcharel", "too pay", "platit", "Ես ուզում եմ վճարել։", "I want to pay.", "Я хочу заплатить."),
    entry("cash", "կանխիկ", "cash", "наличные", "kanchik", "kash", "nalichnye", "Ես կանխիկ եմ վճարում։", "I pay in cash.", "Я плачу наличными."),
    entry("need-money", "ինձ պետք է", "I need", "мне нужно", "indz petk e", "eye need", "mne nuzhno", "Ինձ փող է պետք։", "I need money.", "Мне нужны деньги."),
    entry("please-give", "տվեք", "please give", "дайте", "tvek", "pleez giv", "dayte", "Խնդրում եմ Հաց տվեք։", "Please give me bread.", "Дайте хлеб пожалуйста."),
  ],
  hobbies: [
    entry("play", "խաղում եմ", "I play", "я играю", "khaghum em", "eye play", "ya igrayu", "Ես ֆուտբոլ եմ խաղում։", "I play football.", "Я играю в футбол."),
    entry("football", "ֆուտբոլ", "football", "футбол", "futbol", "foot-bawl", "futbol", "Ես սիրում եմ ֆուտբոլ։", "I like football.", "Я люблю футбол."),
    entry("swim", "լողալ", "to swim", "плавать", "loghal", "too swim", "plavat", "Ես կարող եմ լողալ։", "I can swim.", "Я умею плавать."),
    entry("music", "երաժշտություն", "music", "музыка", "yerazhshtutyun", "myoo-zik", "muzyka", "Ես երաժշտություն եմ լսում։", "I listen to music.", "Я слушаю музыку."),
    entry("watch", "նայում եմ", "I watch", "я смотрю", "nayum em", "eye woch", "ya smotryu", "Ես ֆիլմ եմ նայում։", "I watch a film.", "Я смотрю фильм."),
    entry("film", "ֆիլմ", "film", "фильм", "film", "film", "film", "Այս ֆիլմը լավ է։", "This film is good.", "Этот фильм хороший."),
    entry("can", "կարող եմ", "I can", "я могу", "karogh em", "eye kan", "ya mogu", "Ես կարող եմ լողալ։", "I can swim.", "Я умею плавать."),
    entry("cannot", "չեմ կարող", "I cannot", "я не могу", "chem karogh", "eye kan-not", "ya ne mogu", "Ես չեմ կարող լողալ։", "I cannot swim.", "Я не умею плавать."),
    entry("dance", "պարել", "to dance", "танцевать", "parel", "too dans", "tantsevat", "Ես կարող եմ պարել։", "I can dance.", "Я умею танцевать."),
    entry("hobby", "հոբբի", "hobby", "хобби", "hobbi", "hob-ee", "khobbi", "Իմ հոբբին ֆուտբոլն է։", "My hobby is football.", "Моё хобби футбол."),
    entry("read-verb", "կարդում եմ", "I read", "я читаю", "kardum em", "eye reed", "ya chitayu", "Ես ամեն օր կարդում եմ։", "I read every day.", "Я читаю каждый день."),
    entry("sport", "սպորտ", "sport", "спорт", "sport", "sport", "sport", "Ես սիրում եմ սպորտ։", "I like sport.", "Я люблю спорт."),
    entry("listen", "լսում եմ", "I listen", "я слушаю", "lsum em", "eye lis-en", "ya slushayu", "Ես երաժշտություն եմ լսում։", "I listen to music.", "Я слушаю музыку."),
    entry("walk", "զբոսնել", "to walk", "гулять", "zbosnel", "too wawk", "gulyat", "Ես երեկոյան զբոսնում եմ։", "I walk in the evening.", "Я гуляю вечером."),
  ],
  school: [
    entry("teacher", "ուսուցիչ", "teacher", "учитель", "usutsich", "tee-cher", "uchitel", "Իմ ուսուցիչը բարի է։", "My teacher is kind.", "Мой учитель добрый."),
    entry("homework", "տնային աշխատանք", "homework", "домашняя работа", "tnayin ashkhatank", "hohm-wurk", "domashnyaya rabota", "Ես տնային աշխատանք ունեմ։", "I have homework.", "У меня есть домашняя работа."),
    entry("classroom", "դասարան", "classroom", "класс", "dasaran", "klas-room", "klass", "դասարանը մեծ է։", "The classroom is big.", "Класс большой."),
    entry("study", "սովորում եմ", "I study", "я учу", "sovorum em", "eye stud-ee", "ya uchu", "Ես անգլերեն եմ սովորում։", "I study English.", "Я учу английский."),
    entry("write", "գրում եմ", "I write", "я пишу", "grum em", "eye rite", "ya pishu", "Ես ամեն օր եմ գրում։", "I write every day.", "Я пишу каждый день."),
    entry("nurse", "բուժքույր", "nurse", "медсестра", "buzhkuyr", "nurs", "medsestra", "Նա բուժքույր է։", "She is a nurse.", "Она медсестра."),
    entry("driver", "վարորդ", "driver", "водитель", "varord", "dry-ver", "voditel", "Նա վարորդ է։", "He is a driver.", "Он водитель."),
    entry("waiter", "մատուցող", "waiter", "официант", "matutsogh", "way-ter", "ofitsiant", "Նա մատուցող է։", "He is a waiter.", "Он официант."),
    entry("work-noun", "աշխատանք", "work", "работа", "ashkhatank", "wurk", "rabota", "Իմ աշխատանքը այստեղ է։", "My work is here.", "Моя работа здесь."),
    entry("busy", "զբաղված", "busy", "занятый", "zbaghvats", "biz-ee", "zanyaty", "Ես այսօր զբաղված եմ։", "I am busy today.", "Я сегодня занят."),
    entry("help-verb", "օգնել", "to help", "помогать", "ognel", "too help", "pomogat", "Ես կարող եմ օգնել։", "I can help.", "Я могу помочь."),
    entry("english", "անգլերեն", "English", "английский", "angleren", "ing-lish", "angliysky", "Ես անգլերեն եմ սովորում։", "I study English.", "Я учу английский."),
  ],
  everyday: [
    entry("weather", "եղանակ", "weather", "погода", "yeghanak", "weth-er", "pogoda", "Այսօր եղանակը լավ է։", "The weather is good today.", "Сегодня погода хорошая."),
    entry("sunny", "արևոտ", "sunny", "солнечный", "arevot", "sun-ee", "solnechny", "Այսօր արևոտ է։", "It is sunny today.", "Сегодня солнечно."),
    entry("rainy", "անձրևոտ", "rainy", "дождливый", "andzrevot", "ray-nee", "dozhdlivy", "Այսօր անձրևոտ է։", "It is rainy today.", "Сегодня дождливо."),
    entry("hot", "տաք", "hot", "жаркий", "tak", "hot", "zharky", "Այսօր տաք է։", "It is hot today.", "Сегодня жарко."),
    entry("cold", "ցուրտ", "cold", "холодный", "tsurt", "kohld", "kholodny", "Այսօր ցուրտ է։", "It is cold today.", "Сегодня холодно."),
    entry("coat", "վերարկու", "coat", "пальто", "verarku", "koht", "palto", "Իմ վերարկուն նոր է։", "My coat is new.", "Моё пальто новое."),
    entry("shirt", "վերնաշապիկ", "shirt", "рубашка", "vernashapik", "shurt", "rubashka", "Այս վերնաշապիկը կապույտ է։", "This shirt is blue.", "Эта рубашка синяя."),
    entry("shoes", "կոշիկ", "shoes", "обувь", "koshik", "shooz", "obuv", "Իմ կոշիկները նոր են։", "My shoes are new.", "Моя обувь новая."),
    entry("head", "գլուխ", "head", "голова", "glukh", "hed", "golova", "Իմ գլուխը ցավում է։", "My head hurts.", "У меня болит голова."),
    entry("hand", "ձեռք", "hand", "рука", "dzerk", "hand", "ruka", "Իմ ձեռքը այստեղ է։", "My hand is here.", "Моя рука здесь."),
    entry("big", "մեծ", "big", "большой", "mets", "big", "bolshoy", "Այս տունը մեծ է։", "This house is big.", "Этот дом большой."),
    entry("small", "փոքր", "small", "маленький", "pokr", "small", "malenky", "Այս սենյակը փոքր է։", "This room is small.", "Эта комната маленькая."),
    entry("good", "լավ", "good", "хороший", "lav", "good", "khoroshy", "Այս գիրքը լավ է։", "This book is good.", "Эта книга хорошая."),
    entry("bad", "վատ", "bad", "плохой", "vat", "bad", "plokhoy", "Այս ֆիլմը վատ է։", "This film is bad.", "Этот фильм плохой."),
    entry("new", "նոր", "new", "новый", "nor", "nyoo", "novy", "Իմ վերարկուն նոր է։", "My coat is new.", "Моё пальто новое."),
    entry("old", "հին", "old", "старый", "hin", "ohld", "stary", "Այս աթոռը հին է։", "This chair is old.", "Этот стул старый."),
    entry("happy", "ուրախ", "happy", "счастливый", "urakh", "hap-ee", "schastlivy", "Ես ուրախ եմ։", "I am happy.", "Я счастлив."),
    entry("easy-adj", "հեշտ", "easy", "лёгкий", "hesht", "ee-zee", "lyogky", "Այс գիրքը հեշտ է։", "This book is easy.", "Эта книга лёгкая."),
    entry("difficult-adj", "դժվար", "difficult", "трудный", "dzhvar", "dif-i-kult", "trudny", "Այс գիրքը դժվար է։", "This book is difficult.", "Эта книга трудная."),
    entry("beautiful", "գեղեցիկ", "beautiful", "красивый", "geghetsik", "byoo-ti-ful", "krasivy", "Հայաсտանը գեղեցիկ է։", "Armenia is beautiful.", "Армения красивая."),
    entry("yellow", "դեղին", "yellow", "жёлтый", "deghin", "yel-oh", "zhelty", "Այс գիրքը դեղին է։", "This book is yellow.", "Эта книга жёлтая."),
    entry("black", "սեւ", "black", "чёрный", "sev", "blak", "chorny", "Այс կոշիկը սեւ է։", "These shoes are black.", "Эта обувь чёрная."),
    entry("white", "սպիտակ", "white", "белый", "spitak", "wyt", "bely", "Այс շապիկը սպիտակ է։", "This shirt is white.", "Эта рубашка белая."),
    entry("ill", "հիվանդ", "ill", "больной", "hivand", "il", "bolnoy", "Ես հիվանդ եմ։", "I am ill.", "Я болен."),
    entry("sad", "տխուր", "sad", "грустный", "tkhur", "sad", "grustny", "Ես տխուր չեմ։", "I am not sad.", "Я не грустный."),
  ],
  review: [
    entry("i-dont-understand", "չեմ հասկանում", "I do not understand", "я не понимаю", "chem haskanum", "eye do not un-der-stand", "ya ne ponimayu", "Ես չեմ հասկանում։", "I do not understand.", "Я не понимаю."),
    entry("can-you-help", "կարո՞ղ ես օգնել", "can you help", "можешь помочь", "karogh es ognel", "kan yoo help", "mozhesh pomoch", "Կարո՞ղ ես օգնել։", "Can you help?", "Можешь помочь?"),
    entry("of-course", "իհարկե", "of course", "конечно", "iharke", "ov kors", "konechno", "Իհարկե կարող եմ։", "Of course I can.", "Конечно могу."),
    entry("here-you-are", "խնդրեմ", "here you are", "вот пожалуйста", "khndrem", "heer yoo ar", "vot pozhalusta", "խնդրեմ։", "Here you are.", "Вот пожалуйста."),
    entry("just-a-minute", "մի րոպե", "just a minute", "минутку", "mi rope", "just uh min-it", "minutku", "Մի րոպե խնդրում եմ։", "Just a minute please.", "Минутку пожалуйста."),
    entry("i-am-lost", "մոլորվել եմ", "I am lost", "я заблудился", "molorvel em", "eye am lost", "ya zabludilsya", "Ես մոլորվել եմ։", "I am lost.", "Я заблудился."),
    entry("what-does-this-mean", "սա ի՞նչ է նշանակում", "what does this mean", "что это значит", "sa inch e nshanakum", "wot daz this meen", "chto eto znachit", "Սա ի՞նչ է նշանակում։", "What does this mean?", "Что это значит?"),
    entry("come-imp", "արի", "come", "иди", "ari", "kum", "idi", "Արի այստեղ։", "Come here.", "Иди сюда."),
    entry("open-imp", "բացիր", "open", "открой", "batsir", "oh-pen", "otkroy", "Բացիր դուռը։", "Open the door.", "Открой дверь."),
    entry("close-imp", "փակիր", "close", "закрой", "pakir", "klohz", "zakroy", "Փակիր դուռը։", "Close the door.", "Закрой дверь."),
    entry("sit-imp", "նստիր", "sit down", "сядь", "nstir", "sit down", "syad", "Նստիր խնդրում եմ։", "Sit down please.", "Сядь пожалуйста."),
    entry("why-q", "ինչու", "why", "почему", "inchu", "wy", "pochemu", "Ինչու ես տանն ես։", "Why are you at home?", "Почему ты дома?"),
    entry("but-conj", "բայց", "but", "но", "bayts", "but", "no", "Ես հոգնած եմ բայց ես աշխատում եմ։", "I am tired but I work.", "Я устал но я работаю."),
    entry("or-conj", "կամ", "or", "или", "kam", "or", "ili", "Թեյ կամ сուրճ։", "Tea or coffee.", "Чай или кофе."),
    entry("because-conj", "որովհետև", "because", "потому что", "vorovhetev", "bi-kawz", "potomu chto", "Ես տանն եմ որովհետև հոգնած եմ։", "I am at home because I am tired.", "Я дома потому что устал."),
  ],
};
