import { LEXICON_A2, SENTENCES_A2, type A2UnitKey } from "./lexicon-a2";
import type { Lexeme } from "./types";

export type { Lexeme } from "./types";

export type A1UnitKey = "greetings" | "introduce" | "family" | "numbers";
export type UnitKey = A1UnitKey | A2UnitKey;

const LEXICON_A1: Record<A1UnitKey, Lexeme[]> = {
  greetings: [
    {
      key: "hello",
      hy: "բարև",
      en: "hello",
      ru: "привет",
      hyPron: "barev",
      enPron: "heh-loh",
      ruPron: "privet",
      exampleHy: "Բարև, ինչպե՞ս ես։",
      exampleEn: "Hello, how are you?",
      exampleRu: "Привет, как дела?",
    },
    {
      key: "goodbye",
      hy: "ցտեսություն",
      en: "goodbye",
      ru: "до свидания",
      hyPron: "tstesutyun",
      enPron: "good-bye",
      ruPron: "do svidaniya",
      exampleHy: "Ցտեսություն, կհանդիպենք վաղը։",
      exampleEn: "Goodbye, see you tomorrow.",
      exampleRu: "До свидания, увидимся завтра.",
    },
    {
      key: "thanks",
      hy: "շնորհակալություն",
      en: "thank you",
      ru: "спасибо",
      hyPron: "shnorhakalutyun",
      enPron: "thank you",
      ruPron: "spasibo",
      exampleHy: "Շնորհակալություն օգնության համար։",
      exampleEn: "Thank you for your help.",
      exampleRu: "Спасибо за помощь.",
    },
    {
      key: "please",
      hy: "խնդրում եմ",
      en: "please",
      ru: "пожалуйста",
      hyPron: "khndrum em",
      enPron: "pleez",
      ruPron: "pazhalusta",
      exampleHy: "Խնդրում եմ, նստիր։",
      exampleEn: "Please sit down.",
      exampleRu: "Пожалуйста, садись.",
    },
    {
      key: "yes",
      hy: "այո",
      en: "yes",
      ru: "да",
      hyPron: "ayo",
      enPron: "yes",
      ruPron: "da",
      exampleHy: "Այո, ես համաձայն եմ։",
      exampleEn: "Yes, I agree.",
      exampleRu: "Да, я согласен.",
    },
    {
      key: "no",
      hy: "ոչ",
      en: "no",
      ru: "нет",
      hyPron: "voch",
      enPron: "noh",
      ruPron: "nyet",
      exampleHy: "Ոչ, շնորհակալ եմ։",
      exampleEn: "No, thank you.",
      exampleRu: "Нет, спасибо.",
    },
    {
      key: "morning",
      hy: "բարի լույս",
      en: "good morning",
      ru: "доброе утро",
      hyPron: "bari luys",
      enPron: "good morning",
      ruPron: "dobroye utro",
      exampleHy: "Բարի լույս, Անի։",
      exampleEn: "Good morning, Ani.",
      exampleRu: "Доброе утро, Ани.",
    },
    {
      key: "how-are-you",
      hy: "ինչպե՞ս ես",
      en: "how are you",
      ru: "как дела",
      hyPron: "inchpes es",
      enPron: "how are you",
      ruPron: "kak dela",
      exampleHy: "Ինչպե՞ս ես այսօր։",
      exampleEn: "How are you today?",
      exampleRu: "Как дела сегодня?",
    },
  ],
  introduce: [
    {
      key: "i",
      hy: "ես",
      en: "I",
      ru: "я",
      hyPron: "yes",
      enPron: "eye",
      ruPron: "ya",
      exampleHy: "Ես ուսանող եմ։",
      exampleEn: "I am a student.",
      exampleRu: "Я студент.",
    },
    {
      key: "my-name",
      hy: "իմ անունն է",
      en: "my name is",
      ru: "меня зовут",
      hyPron: "im anunn e",
      enPron: "my name is",
      ruPron: "menya zovut",
      exampleHy: "Իմ անունն է Արմեն։",
      exampleEn: "My name is Armen.",
      exampleRu: "Меня зовут Армен.",
    },
    {
      key: "student",
      hy: "ուսանող",
      en: "student",
      ru: "студент",
      hyPron: "usanogh",
      enPron: "stoo-dent",
      ruPron: "student",
      exampleHy: "Ես ուսանող եմ։",
      exampleEn: "I am a student.",
      exampleRu: "Я студент.",
    },
    {
      key: "armenia",
      hy: "Հայաստան",
      en: "Armenia",
      ru: "Армения",
      hyPron: "Hayastan",
      enPron: "ar-mee-nee-uh",
      ruPron: "Armeniya",
      exampleHy: "Ես Հայաստանից եմ։",
      exampleEn: "I am from Armenia.",
      exampleRu: "Я из Армении.",
    },
    {
      key: "from",
      hy: "ից եմ",
      en: "I am from",
      ru: "я из",
      hyPron: "its em",
      enPron: "I am from",
      ruPron: "ya iz",
      exampleHy: "Ես Երևանից եմ։",
      exampleEn: "I am from Yerevan.",
      exampleRu: "Я из Еревана.",
    },
    {
      key: "nice-meet",
      hy: "հաճելի է ծանոթանալ",
      en: "nice to meet you",
      ru: "приятно познакомиться",
      hyPron: "hajeli e tsanotanal",
      enPron: "nice to meet you",
      ruPron: "priyatno poznakomitsya",
      exampleHy: "Հաճելի է ծանոթանալ։",
      exampleEn: "Nice to meet you.",
      exampleRu: "Приятно познакомиться.",
    },
  ],
  family: [
    {
      key: "family",
      hy: "ընտանիք",
      en: "family",
      ru: "семья",
      hyPron: "yntanik",
      enPron: "fam-uh-lee",
      ruPron: "semya",
      exampleHy: "Իմ ընտանիքը մեծ է։",
      exampleEn: "My family is big.",
      exampleRu: "Моя семья большая.",
    },
    {
      key: "mother",
      hy: "մայր",
      en: "mother",
      ru: "мама",
      hyPron: "mayr",
      enPron: "muh-ther",
      ruPron: "mama",
      exampleHy: "Իմ մայրը բարի է։",
      exampleEn: "My mother is kind.",
      exampleRu: "Моя мама добрая.",
    },
    {
      key: "father",
      hy: "հայր",
      en: "father",
      ru: "папа",
      hyPron: "hayr",
      enPron: "fah-ther",
      ruPron: "papa",
      exampleHy: "Իմ հայրը աշխատում է։",
      exampleEn: "My father works.",
      exampleRu: "Мой папа работает.",
    },
    {
      key: "brother",
      hy: "եղբայր",
      en: "brother",
      ru: "брат",
      hyPron: "yeghbayr",
      enPron: "bruh-ther",
      ruPron: "brat",
      exampleHy: "Ես ունեմ եղբայր։",
      exampleEn: "I have a brother.",
      exampleRu: "У меня есть брат.",
    },
    {
      key: "sister",
      hy: "քույր",
      en: "sister",
      ru: "сестра",
      hyPron: "kuyr",
      enPron: "sis-ter",
      ruPron: "sestra",
      exampleHy: "Իմ քույրը երգում է։",
      exampleEn: "My sister sings.",
      exampleRu: "Моя сестра поёт.",
    },
    {
      key: "child",
      hy: "երեխա",
      en: "child",
      ru: "ребёнок",
      hyPron: "erekha",
      enPron: "chyld",
      ruPron: "rebyonok",
      exampleHy: "Երեխան խաղում է։",
      exampleEn: "The child is playing.",
      exampleRu: "Ребёнок играет.",
    },
  ],
  numbers: [
    {
      key: "one",
      hy: "մեկ",
      en: "one",
      ru: "один",
      hyPron: "mek",
      enPron: "wun",
      ruPron: "odin",
      exampleHy: "Ես ունեմ մեկ եղբայր։",
      exampleEn: "I have one brother.",
      exampleRu: "У меня один брат.",
    },
    {
      key: "two",
      hy: "երկու",
      en: "two",
      ru: "два",
      hyPron: "yerku",
      enPron: "too",
      ruPron: "dva",
      exampleHy: "Երկու բաժակ սուրճ։",
      exampleEn: "Two cups of coffee.",
      exampleRu: "Две чашки кофе.",
    },
    {
      key: "three",
      hy: "երեք",
      en: "three",
      ru: "три",
      hyPron: "yerek",
      enPron: "three",
      ruPron: "tri",
      exampleHy: "Երեք օր։",
      exampleEn: "Three days.",
      exampleRu: "Три дня.",
    },
    {
      key: "five",
      hy: "հինգ",
      en: "five",
      ru: "пять",
      hyPron: "hing",
      enPron: "five",
      ruPron: "pyat",
      exampleHy: "Հինգ գիրք։",
      exampleEn: "Five books.",
      exampleRu: "Пять книг.",
    },
    {
      key: "ten",
      hy: "տասը",
      en: "ten",
      ru: "десять",
      hyPron: "tasy",
      enPron: "ten",
      ruPron: "desyat",
      exampleHy: "Տասը րոպե։",
      exampleEn: "Ten minutes.",
      exampleRu: "Десять минут.",
    },
  ],
};

export const LEXICON: Record<UnitKey, Lexeme[]> = {
  ...LEXICON_A1,
  ...LEXICON_A2,
};

const SENTENCES_A1: Record<A1UnitKey, Array<{ hy: string; en: string; ru: string }>> = {
  greetings: [
    { hy: "Բարև, ինչպե՞ս ես", en: "Hello how are you", ru: "Привет как дела" },
    { hy: "Շնորհակալություն օգնության համար", en: "Thank you for your help", ru: "Спасибо за помощь" },
  ],
  introduce: [
    { hy: "Ես ուսանող եմ", en: "I am a student", ru: "Я студент" },
    { hy: "Իմ անունն է Արմեն", en: "My name is Armen", ru: "Меня зовут Армен" },
  ],
  family: [
    { hy: "Իմ ընտանիքը մեծ է", en: "My family is big", ru: "Моя семья большая" },
    { hy: "Ես ունեմ եղբայր", en: "I have a brother", ru: "У меня есть брат" },
  ],
  numbers: [
    { hy: "Ես ունեմ երկու քույր", en: "I have two sisters", ru: "У меня две сестры" },
  ],
};

export const SENTENCES: Record<UnitKey, Array<{ hy: string; en: string; ru: string }>> = {
  ...SENTENCES_A1,
  ...SENTENCES_A2,
};
