import type { A1UnitKey } from "./lexicon-a1";

type Line = { hy: string; en: string; ru: string };

export const SENTENCES_A1: Record<A1UnitKey, Line[]> = {
  greetings: [
    { hy: "Ինչպես ես այսօր", en: "How are you today", ru: "Как дела сегодня" },
    { hy: "Ես լավ եմ", en: "I am fine", ru: "Я в порядке" },
    { hy: "Ներեցեք", en: "Excuse me", ru: "Простите" },
    { hy: "Ինչ է սա", en: "What is this", ru: "Что это" },
    { hy: "Շնորհակալություն օգնության համար", en: "Thank you for your help", ru: "Спасибо за помощь" },
    { hy: "Դու լավ ես", en: "Are you fine", ru: "Ты в порядке" },
    { hy: "Ես լավ չեմ", en: "I am not fine", ru: "Я не в порядке" },
  ],
  introduce: [
    { hy: "Ես ուսանող եմ", en: "I am a student", ru: "Я студент" },
    { hy: "Նա իմ ընկերն է", en: "He is my friend", ru: "Он мой друг" },
    { hy: "Ինչ է քո անունը", en: "What is your name", ru: "Как тебя зовут" },
    { hy: "Իմ անունն է Արմեն", en: "My name is Armen", ru: "Меня зовут Армен" },
    { hy: "Որտեղ ես ապրում", en: "Where do you live", ru: "Где ты живёшь" },
    { hy: "Ես ապրում եմ Երևանում", en: "I live in Yerevan", ru: "Я живу в Ереване" },
    { hy: "Դու ուսանող ես", en: "Are you a student", ru: "Ты студент" },
  ],
  family: [
    { hy: "Իմ ընտանիքը մեծ է", en: "My family is big", ru: "Моя семья большая" },
    { hy: "Ես ունեմ քույր", en: "I have a sister", ru: "У меня есть сестра" },
    { hy: "Ես քույր չունեմ", en: "I do not have a sister", ru: "У меня нет сестры" },
    { hy: "Սա քո մայրն է", en: "This is your mother", ru: "Это твоя мама" },
    { hy: "Նա եղբայր ունի", en: "He has a brother", ru: "У него есть брат" },
    { hy: "Սա մեր տունն է", en: "This is our home", ru: "Это наш дом" },
  ],
  numbers: [
    { hy: "Ես ունեմ երկու գիրք", en: "I have two books", ru: "У меня две книги" },
    { hy: "Քանի գիրք ունես", en: "How many books do you have", ru: "Сколько у тебя книг" },
    { hy: "Ժամը քանիսն է", en: "What time is it", ru: "Который час" },
    { hy: "Ժամը տասն է", en: "It is ten o clock", ru: "Сейчас десять часов" },
    { hy: "Ես աշխատում եմ երկուշաբթի", en: "I work on Monday", ru: "Я работаю в понедельник" },
    { hy: "Երբ ես աշխատում", en: "When do you work", ru: "Когда ты работаешь" },
  ],
  food: [
    { hy: "Ես մի սուրճ եմ ուզում", en: "I want a coffee", ru: "Я хочу один кофе" },
    { hy: "Սա մի խնձոր է", en: "This is an apple", ru: "Это яблоко" },
    { hy: "Ես թեյ չեմ ուզում", en: "I do not want tea", ru: "Я не хочу чай" },
    { hy: "Ես սիրում եմ այս հացը", en: "I like this bread", ru: "Я люблю этот хлеб" },
    { hy: "Դու սուրճ ես ուզում", en: "Do you want a coffee", ru: "Ты хочешь кофе" },
    { hy: "Այդ հացը լավ է", en: "The bread is good", ru: "Этот хлеб хороший" },
  ],
  places: [
    { hy: "Որտեղ է տունը", en: "Where is the home", ru: "Где дом" },
    { hy: "Ես տուն եմ գնում", en: "I go home", ru: "Я иду домой" },
    { hy: "Գիրքը սեղանի վրա է", en: "The book is on the table", ru: "Книга на столе" },
    { hy: "Սենյակում աթոռ կա", en: "There is a chair in the room", ru: "В комнате есть стул" },
    { hy: "Երկու պատուհան կա", en: "There are two windows", ru: "Есть два окна" },
    { hy: "Սրճարանը այստեղ չէ", en: "The cafe is not here", ru: "Кафе не здесь" },
  ],
  routine: [
    { hy: "Ես ամեն օր գնում եմ դպրոց", en: "I go to school every day", ru: "Я каждый день хожу в школу" },
    { hy: "Նա ամեն օր աշխատում է", en: "He works every day", ru: "Он работает каждый день" },
    { hy: "Ես երեկոյան չեմ աշխատում", en: "I do not work in the evening", ru: "Я вечером не работаю" },
    { hy: "Նա այսօր աշխատում է", en: "Does she work today", ru: "Она сегодня работает" },
    { hy: "Դու առավոտյան աշխատում ես", en: "Do you work in the morning", ru: "Ты работаешь утром" },
    { hy: "Ես միշտ առավոտյան եմ ուտում", en: "I always eat in the morning", ru: "Я всегда ем утром" },
  ],
  shopping: [
    { hy: "Ես ուզում եմ հաց գնել", en: "I want to buy bread", ru: "Я хочу купить хлеб" },
    { hy: "Որքան է գինը", en: "How much is this", ru: "Сколько это стоит" },
    { hy: "Կարող եմ սուրճ ունենալ", en: "Can I have a coffee", ru: "Можно мне кофе" },
    { hy: "Ես քարտով եմ վճարում", en: "I pay by card", ru: "Я плачу картой" },
    { hy: "Ինձ փող է պետք", en: "I need money", ru: "Мне нужны деньги" },
    { hy: "Խնդրեմ ձեր հացը", en: "Here you are", ru: "Вот пожалуйста" },
  ],
  hobbies: [
    { hy: "Ես ֆուտբոլ եմ խաղում", en: "I play football", ru: "Я играю в футбол" },
    { hy: "Ես կարող եմ լողալ", en: "I can swim", ru: "Я умею плавать" },
    { hy: "Ես չեմ կարող լողալ", en: "I cannot swim", ru: "Я не умею плавать" },
    { hy: "Կարող ես լողալ", en: "Can you swim", ru: "Ты умеешь плавать" },
    { hy: "Ես ֆիլմ եմ նայում", en: "I watch a film", ru: "Я смотрю фильм" },
    { hy: "Ես ամեն օր կարդում եմ", en: "I read every day", ru: "Я читаю каждый день" },
  ],
  school: [
    { hy: "Ես անգլերեն եմ սովորում", en: "I study English", ru: "Я учу английский" },
    { hy: "Նա գրասենյակում է աշխատում", en: "She works in an office", ru: "Она работает в офисе" },
    { hy: "Իմ ուսուցիչը բարի է", en: "My teacher is kind", ru: "Мой учитель добрый" },
    { hy: "Ես տնային աշխատանք ունեմ", en: "I have homework", ru: "У меня есть домашняя работа" },
    { hy: "Նա վարորդ է", en: "He is a driver", ru: "Он водитель" },
    { hy: "Ես այսօր զբաղված եմ", en: "I am busy today", ru: "Я сегодня занят" },
  ],
  everyday: [
    { hy: "Այսօր ցուրտ է", en: "It is cold today", ru: "Сегодня холодно" },
    { hy: "Այսօր արևոտ է", en: "It is sunny today", ru: "Сегодня солнечно" },
    { hy: "Իմ վերարկուն նոր է", en: "My coat is new", ru: "Моё пальто новое" },
    { hy: "Այս տունը մեծ է", en: "This house is big", ru: "Этот дом большой" },
    { hy: "Ես ուրախ եմ", en: "I am happy", ru: "Я счастлив" },
    { hy: "Այս ֆիլմը վատ չէ", en: "This film is not bad", ru: "Этот фильм не плохой" },
  ],
  review: [
    { hy: "Ես ուսանող եմ", en: "I am a student", ru: "Я студент" },
    { hy: "Ես ապրում եմ Երևանում", en: "I live in Yerevan", ru: "Я живу в Ереване" },
    { hy: "Ես ամեն օր գնում եմ դպրոց", en: "I go to school every day", ru: "Я каждый день хожу в школу" },
    { hy: "Ես տանն եմ որովհետև հոգնած եմ", en: "I am at home because I am tired", ru: "Я дома потому что устал" },
    { hy: "Բացիր դուռը", en: "Open the door", ru: "Открой дверь" },
    { hy: "Ես չեմ հասկանում", en: "I do not understand", ru: "Я не понимаю" },
    { hy: "Կարող ես օգնել", en: "Can you help", ru: "Можешь помочь" },
  ],
};
