services:
  db:
    image: postgres:16-alpine
    container_name: lezoo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: lezoo
      POSTGRES_PASSWORD: lezoo
      POSTGRES_DB: lezoo
    ports:
      - "5432:5432"
    volumes:
      - lezoo-pg-data:/var/lib/postgresql/data

volumes:
  lezoo-pg-data:
